name: Deploy code to Github pages
on:
  push:
    branches:
      - 'main'
jobs:
  deploy-to-gh-pages:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to code
        uses: actions/checkout@v4
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install and build the application
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/*
